name: Release NodeJS app # This is the name of the workflow

# Run it on every push to master
on:
  push:
    branches:
      - main

# What do we do
jobs:
  build:
    runs-on: ubuntu-latest
    # What are the steps to build this?
    # Currently the checkout is at v3 according to the readme.
    steps:
      # Just check it out.
      - uses: actions/checkout@v3
      
      # Then we need to log in to the hub
      - name: Log in to the docker hub
        # Current readme says it's on v2.1.0
        uses: docker/login-action@v2.1.0
        # What do we log in with? In the readme.
        with: 
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}
      # After we've logged in and checked out, we want to build&push it to the dockerhub
      # Basically just copypaste from the readme, push and tags are the only required?
      - name: Build&Push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/workflows:latest
        
